Repository jordy1611/NH-JS-Rancid-Tomatillos, pull requests merged in 2020-09, with the labels that each got.

#56 Feature/comment section
  src/App/App.js
  src/App/App.test.js
  src/Comment/Comment.css
  src/Comment/Comment.js
  src/Comment/Comment.test.js
  src/Comments/Comments.css
  src/Comments/Comments.js
  src/Comments/Comments.test.js
  src/Header/Header.test.js
  src/MovieInfo/MovieInfo.js
  src/MovieInfo/MovieInfo.test.js
  src/Posters/Posters.js
  src/dataFetcher.js
Labels: enhancement

#57 Js favoriting
  README.md
  src/App/App.css
  src/App/App.js
  src/Header/Header.css
  src/Header/Header.js
  src/Login/Login.js
  src/MovieInfo/MovieInfo.css
  src/MovieInfo/MovieInfo.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/Posters/Posters.js
  src/assets/favorite.png
  src/assets/notFavorite.png
  src/dataFetcher.js
Labels: enhancement, javascript, react, styling

#59 Add more tests from extra work done from comments and favorites
  src/App/App.test.js
  src/MovieInfo/MovieInfo.test.js
  src/Poster/Poster.js
  src/Poster/Poster.test.js
Labels: javascript, react, testing
