Repository jordy1611/NH-JS-Rancid-Tomatillos, pull requests merged in 2020-08, with the labels that each got.

#16 Jms master branch fix
  package-lock.json
  package.json
  src/App.test.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.test.js
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.test.js
  src/MovieInfo/MovieInfo.css
  src/MovieInfo/MovieInfo.js
  src/MovieInfo/MovieInfo.test.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/Poster/Poster.test.js
  src/Posters/Posters.css
  src/Posters/Posters.js
  src/Posters/Posters.test.js
  src/index.js
Labels: react, testing

#17 Jms styling
  src/App/App.css
  src/Header/Header.css
  src/Login/Login.css
  src/MovieInfo/MovieInfo.css
  src/Poster/Poster.css
  src/Posters/Posters.css
  src/assets/background.jpg
Labels: styling

#27 Test cleanup and username display
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/Login/Login.css
  src/Login/Login.js
  src/Login/Login.test.js
  src/Posters/Posters.test.js
Labels: refactor, styling, testing

#33 Fetch testing
  package-lock.json
  package.json
  src/App/App.test.js
  src/Login/Login.js
  src/Login/Login.test.js
  src/dataFetcher.js
  src/sampleData.js
  src/sampleMovies.js
Labels: testing

#34 Jms submit user rating
  src/App/App.js
  src/Login/Login.css
  src/Login/Login.js
  src/MovieInfo/MovieInfo.css
  src/MovieInfo/MovieInfo.js
  src/Poster/Poster.js
  src/Posters/Posters.js
  src/dataFetcher.js
Labels: initialization, react

#40 User rating display
  src/App/App.js
  src/Header/Header.js
  src/Login/Login.js
  src/Poster/Poster.js
  src/Posters/Posters.js
  src/dataFetcher.js
Labels: enhancement

#41 Jms delete rating
  src/App/App.js
  src/MovieInfo/MovieInfo.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/dataFetcher.js
Labels: enhancement, javascript, react

#44 Router implementation
  package-lock.json
  package.json
  src/App/App.js
  src/Header/Header.js
  src/Login/Login.js
  src/MovieInfo/MovieInfo.js
  src/Poster/Poster.js
  src/index.js
Labels: refactor

#47 Js router change fixes
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.js
  src/Login/Login.css
  src/Login/Login.js
  src/MovieInfo/MovieInfo.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/Poster/Poster.test.js
  src/Posters/Posters.js
  src/Posters/Posters.test.js
  src/sampleData.js
Labels: javascript, react, refactor, testing
